In [33]:
import numpy
#numpy.genfromtxt --> read datasets
drinks = numpy.genfromtxt(r'D:\GitHub\Data-Science\NumPy\Exercise1\drinks.csv', delimiter=",")
print(type(drinks))
print(drinks)  # nan --> not a number, NumPy assigns an na value, which stands for Not Available, when the value doesn't exist. nan and na values are types of missing data.

<class 'numpy.ndarray'>
[[             nan              nan              nan              nan
               nan]
 [             nan   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [             nan   8.90000000e+01   1.32000000e+02   5.40000000e+01
    4.90000000e+00]
 [             nan   2.50000000e+01   0.00000000e+00   1.40000000e+01
    7.00000000e-01]
 [             nan   2.45000000e+02   1.38000000e+02   3.12000000e+02
    1.24000000e+01]
 [             nan   2.17000000e+02   5.70000000e+01   4.50000000e+01
    5.90000000e+00]
 [             nan   1.02000000e+02   1.28000000e+02   4.50000000e+01
    4.90000000e+00]
 [             nan   1.93000000e+02   2.50000000e+01   2.21000000e+02
    8.30000000e+00]
 [             nan   2.10000000e+01   1.79000000e+02   1.10000000e+01
    3.80000000e+00]
 [             nan   2.61000000e+02   7.20000000e+01   2.12000000e+02
    1.04000000e+01]
 [             nan   2.79000000e+02   7.50000000e+01   1.91000000e+02
    9.

In [24]:
# numpy.array() --> constructing array
# ndarray.shape --> find the size of the array
vector = numpy.array([1,2,3,4])
print(vector)
print(vector.shape)
matrix = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)
print(matrix.shape)

[1 2 3 4]
(4,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [84]:
# NumPy data types
'''
bool -- Boolean. Can be True or False.
int -- Integer values. (eg: 10) Can be int16, int32, or int64. The suffix 16, 32, or 64 indicates how long the number can be, in bytes (we'll dive more into bytes later on).
float -- Floating point values. (eg: 10.6). Can be float16, float32, or float64. The suffix 16, 32, or 64 indicates how many numbers after the decimal point the number can have. 
string -- String values. Can be string or unicode. The difference between string and unicode is how the characters are stored by the computer.
'''
vector = numpy.array([1,2,3,4])
print(vector.dtype)
matrix = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix.dtype)
a = numpy.array(['a',"ac"])
print(a.dtype)
b = numpy.array(['a',"ac",3])
print(b.dtype)
print(drinks.dtype)

matrix = numpy.array([[0,2,4,6,8,10],[10,20,40,60,80]])
print(matrix.dtype, matrix.shape)

int32
int32
<U2
<U2
<U75
object (2,)


In [46]:
import numpy
#numpy.genfromtxt --> read datasets
drinks = numpy.genfromtxt(r'D:\GitHub\Data-Science\NumPy\Exercise1\drinks.csv', dtype = 'U75', skip_header = 1, delimiter=",")
print(drinks[0:4])
print(drinks[1][4])
print(drinks[2,3])
print(drinks[10:14])

[['Afghanistan' '0' '0' '0' '0.0']
 ['Albania' '89' '132' '54' '4.9']
 ['Algeria' '25' '0' '14' '0.7']
 ['Andorra' '245' '138' '312' '12.4']]
4.9
14
[['Azerbaijan' '21' '46' '5' '1.3']
 ['Bahamas' '122' '176' '51' '6.3']
 ['Bahrain' '42' '63' '7' '2.0']
 ['Bangladesh' '0' '0' '0' '0.0']]


In [61]:
# When we want to select one entire dimension, and a single element from the other.
matrix = numpy.array([[1,2,3,4], [10,20,30,40], [100,200,300,400], [1000,2000,3000,4000], [10000,20000,30000,40000]])
dtyp1 = matrix[:,0]
print(dtyp1.shape)
print(dtyp1)
dtyp2 = matrix[4,:]
print(dtyp2.shape)
print(dtyp2)

(5,)
[    1    10   100  1000 10000]
(4,)
[10000 20000 30000 40000]


In [67]:
# When we want to select one entire dimension, and a slice of the other.
dtyp1 = matrix[:,0:1]
print(dtyp1.shape)
print(dtyp1)
dtyp2 = matrix[2:,:]
print(dtyp2.shape)
print(dtyp2)



(5, 1)
[[    1]
 [   10]
 [  100]
 [ 1000]
 [10000]]
(3, 4)
[[  100   200   300   400]
 [ 1000  2000  3000  4000]
 [10000 20000 30000 40000]]


In [70]:
# When you want to select a slice of one dimension, and a single element from the other.
dtyp1 = matrix[1:5,2]
print(dtyp1.shape)
print(dtyp1)

dtyp2 = matrix[3,2:4]
print(dtyp2.shape)
print(dtyp2)

(4,)
[   30   300  3000 30000]
(2,)
[3000 4000]


In [69]:
# When we want to slice both dimensions.
dtyp1 = matrix[1:4, 1:3]
print(dtyp1.shape)
print(dtyp1)

dtyp2 = matrix[0:3, 3:4]
print(dtyp2.shape)
print(dtyp2)

(3, 2)
[[  20   30]
 [ 200  300]
 [2000 3000]]
(3, 1)
[[  4]
 [ 40]
 [400]]


In [77]:
# Array comparisons
vector = numpy.array([5,15,35,35])
var1 = vector == 10
var2 = vector == 15
print("var1: " , var1)
print("var2: " , var2)
newvect1 = vector[var1]
newvect2 = vector[var2]
print("newvect1: ", newvect1)
print("newvect2: ", newvect2)


var1:  [False False False False]
var2:  [False  True False False]
newvect1:  []
newvect2:  [15]


In [97]:
matrix = numpy.array([[0,2,4,6,10],[10,20,40,60,80],[100,120,140,10,180],[200,220,10,260,280],[300,320,340,360,380]])
var1 = matrix == 10
#var2 = matrix == 'numbers'
var3 = matrix[:,3] == 10
print("var1: " , var1)
print("var2: " , var2)
print("var3: " , var3)
newvect1 = matrix[var1]
#newvect2 = matrix[var2]
newvect3 = matrix[var3,:]
print("newvect1: ", newvect1)
#print("newvect2: ", newvect2)
print("newvect3: ", newvect3)

var1:  [[False False False False  True]
 [ True False False False False]
 [False False False  True False]
 [False False  True False False]
 [False False False False False]]
var2:  False
var3:  [False False  True False False]
newvect1:  [10 10 10 10]
newvect3:  [[100 120 140  10 180]]


In [134]:
# Find and replace values
vector = numpy.array([2,4,6,8,10])
print(vector.shape)
pos = vector == 5
print(pos)
vector[pos] = 50
print(vector)
pos = vector == 6
print(pos)
vector[pos] = 60
print(vector)

(5,)
[False False False False False]
[ 2  4  6  8 10]
[False False  True False False]
[ 2  4 60  8 10]


In [112]:
# Find and replace values
matrix = numpy.array([[2, 22,24],[4,3,5],[3,5,5 ],[4,9, 4]])
print(matrix.shape)
pos = matrix[:,2] == 5
matrix[pos] = 0
print(matrix)
matrix = numpy.array([[2, 22,24],[4,3,5],[3,5,5 ],[4,9, 4]])
pos = matrix[:,2] == 5
matrix[pos,:] = 0
print(matrix)
matrix = numpy.array([[2, 22,24],[4,3,5],[3,5,5 ],[4,9, 4]])
pos = matrix[:,2] == 5
matrix[pos,2] = 0
print(matrix)

(4, 3)
[[ 2 22 24]
 [ 0  0  0]
 [ 0  0  0]
 [ 4  9  4]]
[[ 2 22 24]
 [ 0  0  0]
 [ 0  0  0]
 [ 4  9  4]]
[[ 2 22 24]
 [ 4  3  0]
 [ 3  5  0]
 [ 4  9  4]]


In [122]:
#Data type conversion
matrix = numpy.array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', ''],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '']])
print(matrix.shape, matrix.dtype)
var1 = matrix[:,4] == ''
print(var1)
matrix[var1,4] = '0'
print(matrix)
vect = numpy.array([1,2,3,4])
print(vect.astype(float))
var2 = matrix[:,4].astype(float)
print(var2)

(5, 5) <U16
[ True False False False  True]
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']]
[ 1.  2.  3.  4.]
[ 0.    0.5   1.62  2.54  0.  ]


In [129]:
#Computation on a vector
print(var2)
print(var2.sum())   #sum()
print(var2.mean())  #mean()
print(var2.max())   #max()
print(var2.min())   #min()


[ 0.    0.5   1.62  2.54  0.  ]
4.66
0.932
2.54
0.0


In [131]:
#Computation on matrix
matrix = numpy.array([[2, 22,24],[4,3,5],[3,5,5 ],[4,9, 4]])
print(matrix)
print(matrix.sum(axis=0))   #0 ==> column
print(matrix.sum(axis=1))   #1 ==> row

[[ 2 22 24]
 [ 4  3  5]
 [ 3  5  5]
 [ 4  9  4]]
[13 39 38]
[48 12 13 17]
